/**
 * AnyType automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonType} from "./CommonType";

/**
 * Represents an any type
 */
export interface AnyType extends CommonType {
    type?: string
}
