/**
 * BooleanType automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ScalarType} from "./ScalarType";

/**
 * Represents a boolean type
 */
export interface BooleanType extends ScalarType {
    type?: string
}
