/**
 * GenericType automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

/**
 * Represents a generic type. A generic type can be used i.e. at a map or array which then can be replaced on reference via the $template keyword
 */
export interface GenericType {
    $generic?: string
}
