/**
 * IntersectionType automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ReferenceType} from "./ReferenceType";

/**
 * Represents an intersection type
 */
export interface IntersectionType {
    description?: string
    allOf?: Array<ReferenceType>
}
