/**
 * IntegerType automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {NumberType} from "./NumberType";

/**
 * Represents an integer type
 */
export interface IntegerType extends NumberType {
    type?: string
}
