/**
 * NumberType automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ScalarType} from "./ScalarType";

/**
 * Represents a number type
 */
export interface NumberType extends ScalarType {
    type?: string
    maximum?: number
    minimum?: number
}
