/**
 * Response automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ReferenceType} from "./ReferenceType";
export interface Response {
    code?: number
    schema?: ReferenceType
}
