/**
 * ScalarType automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {CommonType} from "./CommonType";

/**
 * Represents a scalar type
 */
export interface ScalarType extends CommonType {
    format?: string
    enum?: Array<string | number>
}
