/**
 * Security automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

export interface Security {
    type?: string
    name?: string
    in?: string
    tokenUrl?: string
    authorizationUrl?: string
    scopes?: Array<string>
}
