/**
 * StringType automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {ScalarType} from "./ScalarType";

/**
 * Represents a string type
 */
export interface StringType extends ScalarType {
    type?: string
    maxLength?: number
    minLength?: number
    pattern?: string
}
