/**
 * TypeApi automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {TypeSchema} from "./TypeSchema";
import {Security} from "./Security";
import {Operation} from "./Operation";

/**
 * The TypeApi Root
 */
export interface TypeApi extends TypeSchema {
    baseUrl?: string
    security?: Security
    operations?: Record<string, Operation>
}
